// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package id

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_Success Status = 0
	Status_Error   Status = 1
)

var Status_name = map[int32]string{
	0: "Success",
	1: "Error",
}

var Status_value = map[string]int32{
	"Success": 0,
	"Error":   1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type Generate32BitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Generate32BitRequest) Reset()         { *m = Generate32BitRequest{} }
func (m *Generate32BitRequest) String() string { return proto.CompactTextString(m) }
func (*Generate32BitRequest) ProtoMessage()    {}
func (*Generate32BitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Generate32BitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Generate32BitRequest.Unmarshal(m, b)
}
func (m *Generate32BitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Generate32BitRequest.Marshal(b, m, deterministic)
}
func (m *Generate32BitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Generate32BitRequest.Merge(m, src)
}
func (m *Generate32BitRequest) XXX_Size() int {
	return xxx_messageInfo_Generate32BitRequest.Size(m)
}
func (m *Generate32BitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Generate32BitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Generate32BitRequest proto.InternalMessageInfo

type Generate32BitReply struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=id.Status" json:"status,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Generate32BitReply) Reset()         { *m = Generate32BitReply{} }
func (m *Generate32BitReply) String() string { return proto.CompactTextString(m) }
func (*Generate32BitReply) ProtoMessage()    {}
func (*Generate32BitReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Generate32BitReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Generate32BitReply.Unmarshal(m, b)
}
func (m *Generate32BitReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Generate32BitReply.Marshal(b, m, deterministic)
}
func (m *Generate32BitReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Generate32BitReply.Merge(m, src)
}
func (m *Generate32BitReply) XXX_Size() int {
	return xxx_messageInfo_Generate32BitReply.Size(m)
}
func (m *Generate32BitReply) XXX_DiscardUnknown() {
	xxx_messageInfo_Generate32BitReply.DiscardUnknown(m)
}

var xxx_messageInfo_Generate32BitReply proto.InternalMessageInfo

func (m *Generate32BitReply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Success
}

func (m *Generate32BitReply) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("id.Status", Status_name, Status_value)
	proto.RegisterType((*Generate32BitRequest)(nil), "id.Generate32BitRequest")
	proto.RegisterType((*Generate32BitReply)(nil), "id.Generate32BitReply")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0x86, 0xdd, 0x05, 0x95, 0x26, 0x14, 0x19, 0x42, 0xa4, 0x93, 0xec, 0x49, 0x3a, 0x78, 0xd0,
	0x37, 0x28, 0xa2, 0x4e, 0x1d, 0xf4, 0x09, 0xcc, 0x9d, 0xc3, 0x82, 0xa4, 0xed, 0xae, 0x81, 0x6f,
	0x1f, 0x69, 0x97, 0xc2, 0xeb, 0xff, 0x0d, 0x7c, 0xdf, 0x40, 0x60, 0x48, 0xbf, 0x54, 0x4b, 0xf9,
	0xa0, 0x7b, 0xdb, 0x23, 0x57, 0x52, 0xc4, 0xb0, 0xbb, 0xd0, 0x83, 0x74, 0x63, 0xa9, 0x2c, 0x8e,
	0xca, 0x56, 0xf4, 0x1c, 0xc9, 0x58, 0x71, 0x05, 0xfc, 0xdb, 0x87, 0x6e, 0x42, 0x01, 0x9e, 0xb1,
	0x8d, 0x1d, 0x4d, 0xc2, 0x52, 0x96, 0x85, 0x05, 0xe4, 0x4a, 0xe6, 0xf5, 0xbc, 0x54, 0x5f, 0x82,
	0x21, 0x70, 0x25, 0x13, 0x9e, 0xb2, 0xcc, 0xad, 0xb8, 0x92, 0x87, 0x14, 0xbc, 0xe5, 0x02, 0xb7,
	0xe0, 0xd7, 0x63, 0xdb, 0x92, 0x31, 0x91, 0x83, 0x1b, 0x70, 0xcf, 0x5a, 0xf7, 0x3a, 0x62, 0xc5,
	0x0d, 0xfc, 0x7a, 0x09, 0xc3, 0x13, 0x04, 0x3f, 0x5a, 0x4c, 0x3e, 0x86, 0xb5, 0xc2, 0x7d, 0xbc,
	0x42, 0x86, 0x6e, 0x12, 0xce, 0xdd, 0x9b, 0xdf, 0x2b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6f,
	0xfb, 0x7d, 0x63, 0xef, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Generate32Bit(ctx context.Context, in *Generate32BitRequest, opts ...grpc.CallOption) (*Generate32BitReply, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Generate32Bit(ctx context.Context, in *Generate32BitRequest, opts ...grpc.CallOption) (*Generate32BitReply, error) {
	out := new(Generate32BitReply)
	err := c.cc.Invoke(ctx, "/id.Service/Generate32Bit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Generate32Bit(context.Context, *Generate32BitRequest) (*Generate32BitReply, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Generate32Bit(ctx context.Context, req *Generate32BitRequest) (*Generate32BitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate32Bit not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Generate32Bit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Generate32BitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Generate32Bit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/id.Service/Generate32Bit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Generate32Bit(ctx, req.(*Generate32BitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "id.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate32Bit",
			Handler:    _Service_Generate32Bit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
